openapi: 3.1.0
info:
  title: Incomster API
  version: 1.0.0
paths:
  /incomes:
    get:
      summary: Get incomes
      description: Retrieve a list of incomes with optional filtering.
      parameters:
        - in: query
          name: employee_ids
          schema:
            type: array
            items:
              type: integer
          description: Filter incomes by multiple employee IDs.
        - in: query
          name: min_date
          schema:
            type: integer
          description: Filter incomes created after this date (Unix time).
        - in: query
          name: max_date
          schema:
            type: integer
          description: Filter incomes created before this date (Unix time).
        - in: query
          name: min_amount
          schema:
            type: number
          description: Minimum income amount.
        - in: query
          name: max_amount
          schema:
            type: number
          description: Maximum income amount.
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit the number of returned incomes.
      responses:
        '200':
          description: List of incomes with count and total sum.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomesResponse'
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Add a new income
      description: Add a new income to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomeResponse'
      responses:
        '201':
          description: Income successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomeResponse'
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /incomes/{id}:
    get:
      summary: Get specific income
      description: Retrieve a single income by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the income to retrieve.
      responses:
        '200':
          description: The requested income.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomeResponse'
        '404':
          description: Income not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete an income
      description: Delete a specific income by its ID and return the deleted income.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the income to delete.
      responses:
        '200':
          description: Deleted income.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomeResponse'
        '404':
          description: Income not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    IncomeResponse:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the income.
        employee_id:
          type: integer
          description: ID of the employee who submitted the income.
        amount:
          type: number
          description: The income amount.
        comment:
          type: string
          nullable: true
          description: Optional comment for the income.
        created_at:
          type: integer
          description: The date and time when the income was created (Unix time).

    IncomesResponse:
      type: object
      properties:
        incomes:
          type: array
          items:
            $ref: '#/components/schemas/IncomeResponse'
        count:
          type: integer
          description: Total number of incomes retrieved.
        sum:
          type: number
          description: Total sum of all retrieved incomes.

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.